name: 🚀 CI/CD

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Load Cached Poetry
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-dependencies

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true

      - name: Load Cached Python Dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: python-dependencies-${{ hashFiles('**/poetry.lock') }}

      - name: Install Python Dependencies
        run: poetry install

      - name: Fix APT Cache Permission
        run: sudo chown -R "$(id -u)" /var/cache/apt

      - name: Load Cached APT Dependencies
        uses: actions/cache@v1
        with:
          path: /var/cache/apt/archives
          key: apt-dependencies

      - name: Install APT Dependencies
        run: |
          sudo apt-get update -yq
          sudo apt-get install -y --no-install-recommends debhelper fakeroot

      - name: Fix APT Cache Permission
        run: sudo chown -R "$(id -u)" /var/cache/apt/archives

      - name: Run black
        run: poetry run black src tests --check

      - name: Run isort
        run: poetry run isort src tests --check

      - name: Run flake8
        run: poetry run flake8 src tests

      - name: Run mypy
        run: poetry run mypy --show-error-codes src

      - name: Run pytest
        run: poetry run pytest --cov=src --cov-report=term-missing tests

      - name: Generate coverage report
        shell: bash
        run: poetry run coverage xml

      - uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml

  build:
    runs-on: ubuntu-latest
    container: wakemeops/debian:bullseye-slim
    needs: [tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          install_packages \
            poetry \
            python3-dev \
            ca-certificates \
            binutils

      - name: Build wakemebot single binary application
        run: |
          ./build-single-binary-application.sh
          mv dist/wakemebot wakemebot_linux_amd64

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: wakemebot_linux_amd64
          path: wakemebot_linux_amd64
          retention-days: 2

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install clog-cli
        run: |
          curl -sSL https://raw.githubusercontent.com/upciti/wakemeops/main/assets/install_repository | sudo bash -s dev
          sudo apt-get update -yq
          sudo apt-get install -y clog-cli

      - name: Build Release Changelog
        run: |
          clog --setversion $(git tag --sort=creatordate | tail -n1) \
               --from $(git tag --sort=creatordate | tail -n2 | head -n1) \
               -o changelog.md \
               -r https://github.com/upciti/wakemebot

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: wakemebot_linux_amd64

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: changelog.md
          files: wakemebot_linux_amd64
